lib/bandit/http2/stream_task.ex

Replaced the `map` & `join` with a `map_join` and prepend the resulting `combinated_cookie` instead of list concatenation.

Minor improvements to `combine_cookie_crumbs/1`

---

lib/bandit/http1/adapter.ex

I replaced the `Regex` matching with a pattern match for a `nil` connection header and otherwise `downcase` the `connection_header` and match it in a case.
This should (in theory) be faster.

Avoid regex matching in `should_keepalive?/2`

---

lib/bandit/initial_handler.ex
test/bandit/initial_handler_test.exs
test/support/client_helpers.ex
test/support/simple_h2_client.ex

Explicitly handle the `http/1.1` and `http/1.0` ALPN from the client.

Explicitly handle HTTP1 ALPN

---

lib/bandit/websocket/handshake.ex
test/bandit/websocket/http1_handshake_test.exs

Since header fields are case-insensitive, I added a helper which downcases the fields before comparison.
This is needed, so the Autobahn tests work, since Autobahn uses:
```
Upgrade: WebSocket
Connection: Upgrade
```
in headers

Make header field handling case-insensitive

---

lib/bandit/http1/adapter.ex
lib/bandit/http2/stream.ex
lib/bandit/websocket/handshake.ex

- Use `String.downcase/2` in `:ascii` mode
- Boolean `and` instead of `&&` in `get_http_protocol` (since all elements are booleans)
- Simplify `do_read_chunk` by using `:binary.split/2` instead of `:binary.match/2` and binary pattern matching

Minor performance improvements

---

lib/bandit/websocket/frame.ex

Improve masking.
This is about 3x (for small inputs) - 10x (for large inputs) faster (also uses less memory): [Benchmark](https://gist.github.com/moogle19/cd58b4618cac33a44fc7d8561eb99455)
Limits/Performance section of Autobahn with the current version (left) and the `fast_mask` version (right):

Faster masking

---

README.md
lib/bandit/http2/stream_collection.ex
lib/bandit/websocket/handshake.ex

Hi,
This is a small suggestion to remove some calls to `Enum.map/2` to avoid intermediate structures when there is a way of doing it in one pass.
While it most probably won't result in a noticeable speedup, it also simplifies the code.
The second unrelated commit just adds syntax highlighting to some code in the readme.

Remove un-necessary Enum.map/2

---

lib/bandit/websocket/handshake.ex
test/support/simple_websocket_client.ex

The Websocket upgrade was failing, when the connection header had more than 1 value (e.g `Connection: keep-alive, Upgrade` which is used by the Phoenix live_reload socket). 
I updated the `header_contains?/3` to handle these cases.

Fix header parsing in Websocket upgrade

---

lib/bandit/http2/connection.ex
lib/bandit/http2/stream.ex
test/bandit/http2/protocol_test.exs
test/support/client_helpers.ex
test/test_helper.exs

While test-driving 1.15 I noticed some warnings.
`Logger.warn/2` will be deprecated in favor of `Logger.warning/2`. 
As it is available since `1.11` and Bandit defines `~> 1.11` as elixir version this shouldn't be a problem.
And `mix format` defaults to `~c` for charlist now.

Fix Elixir 1.15 deprecations / warnings

---

lib/bandit/http1/adapter.ex
lib/bandit/http1/handler.ex
test/bandit/http1/request_test.exs
test/support/server_helpers.ex

Currently only the `:abs_path` returned by `:erlang.decode_packet/3` are handled.
This adds support for the other types by extracting the `path` component of the [HttpUri](https://www.erlang.org/doc/man/erlang.html#decode_packet-3) returned by `decode_packet/3`.
Because of the URL construction [here](https://github.com/mtrudel/bandit/blob/f01d156b9b10cf51b74eaea4938361097d50f9f4/lib/bandit/http1/handler.ex#L42), the path **must** start with a slash, otherwise that will fail, therefore a slash is added to the start of the path if it is not present.
I am not sure if this is the correct or best way to handle the paths, so feedback would be appreciated!

Handle all path types

---

lib/bandit/http1/adapter.ex

byte_size/1 only accepts bitstrings,
Whereas IO.iodata_length accepts iodata.
Implements fix mentioned in #63

fix: chunk callback expects iodata in second argument

---

lib/bandit/http1/adapter.ex
test/bandit/http1/request_test.exs

I looked over the content-length parsing again and found a solution, which should be as fast as before for single content-length values (which should be the default case most of the time), but a bit slower for multiple values.
Benchmark:
```bash
Name              ips        average  deviation         median         99th %
current        1.77 M      565.85 ns  ±5890.01%         458 ns        1417 ns
fast           1.63 M      612.88 ns  ±4632.45%         500 ns         667 ns
Comparison: 
current        1.77 M
fast           1.63 M - 1.08x slower +47.04 ns
Memory usage statistics:
Name       Memory usage
current           736 B
fast              728 B - 0.99x memory usage -8 B
**All measurements for memory usage were the same**
Name              ips        average  deviation         median …
```

Faster content-length parsing

---

lib/bandit/phoenix_adapter.ex

A purely code-cosmetic fix to `port_to_integer`. The parens were not necessary and conflict stylistically with the `port_to_integer` definition above it. 
I feel like I've had this same thing happen to me before when having `mix format` auto execute on save.  
Looks like my linter also removed some empty spaces. Nice. 🤷

fix: remove unnecessary parens

---

lib/bandit.ex
test/bandit/server_test.exs

Use references as unique process identifiers to support multiple Bandits

---

lib/bandit.ex

Brings the count in line with plug_cowboy reflected in improved TTFB benchmarks

Create 100 acceptor processes by default

---

lib/bandit/websocket/frame.ex

Inlining the mask function seems to yield some more performance benefits.
<details>
<summary>Benchmark</summary>
```elixir
Operating System: macOS
CPU Information: Apple M1 Pro
Number of Available Cores: 10
Available memory: 32 GB
Elixir 1.15.0-dev
Erlang 25.2.1
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
reduction time: 0 ns
parallel: 1
inputs: huge, large, medium, micro, small, tiny
Estimated total run time: 2.80 min
Benchmarking current with input huge ...
Benchmarking current with input large ...
Benchmarking current with input medium ...
Benchmarking current with input micro ...
Benchmarking current with input small ...
Benchmarking current with input tiny ...
Benchmarking current_inlined with input huge ...
Benchmarking …
```

Inline masking

---

lib/bandit/http1/adapter.ex

As an alternative to [Add some common HTTP status codes #94](https://github.com/mtrudel/bandit/pull/94), this PR removes Bandit's logic for generating status text from HTTP status codes and replaces it with [`Plug.Conn.Status.reason_phrase/1`](https://github.com/elixir-plug/plug/blob/d7940552e365e0d3245bb78ca99429ea5c324f7d/lib/plug/conn/status.ex#L146-L174).
Thanks to @moogle19 for [suggesting this](https://github.com/mtrudel/bandit/issues/93#issuecomment-1420385066).
The [status code list from Plug](https://github.com/elixir-plug/plug/blob/d7940552e365e0d3245bb78ca99429ea5c324f7d/lib/plug/conn/status.ex#L8-L72) matches the existing Bandit list, plus what was added in #94, plus HTTP 306 Switch Proxy, a deprecated status code in reserved space that some servers may return when presumably …

Use Plug.Conn.Status.reason_phrase/1

---

lib/bandit/headers.ex
test/bandit/http1/request_test.exs
test/bandit/http2/protocol_test.exs

Good morning!
Last time I found something, I missed my chance to get a PR in, so I'm hoping to rectify that this time ;)
I was seeing errors when accessing my local server using its IPv6 address as hostname (some HTTP clients unfortunately convert localhost to `[::1]` automatically). So I did some digging and discovered that bandit just didn't cover this case at all.
I think this PR should just about cover it. Let me know if you'd prefer to see something changed in here.
Also I have to say, the more I read the code the more impressed I am with bandit / thousand island. It isn't a trivial task to make code that is this clear, let alone an http server implementation. I was able to find and fix this (including puzzling over how to make the actual function body not look insane) in about 40 …

Fix host header consumption for ipv6 hostnames

---

lib/bandit/websocket/connection.ex
lib/bandit/websocket/socket.ex
mix.exs
mix.lock
test/bandit/websocket/protocol_test.exs
test/bandit/websocket/sock_test.exs
test/bandit/websocket/upgrade_test.exs

Implements Bandit support for close tuples as described in https://github.com/phoenixframework/websock_adapter/issues/2; supports callbacks to return {:stop, reason, code, state} or {:stop, reason, {code, detail}, state}.
Pairs with / requires https://github.com/phoenixframework/websock/pull/6.

Support extended connection close return values

---

lib/bandit/http2/connection.ex
lib/bandit/http2/handler.ex
lib/bandit/http2/stream.ex

Relevant to your interests @danschultzer

Stop requiring HTTP/2 adapter commands to come from stream owner process

---

lib/bandit.ex
test/bandit/server_test.exs

I want to be able to silence the info log that Bandit by default prints. The `:log` option is lifted from how it's usually dealt with in Plug and Phoenix.
But I wonder if there should be an info log by default? With `Plug.Cowboy` and `:httpd` there are no info log for server start. This is something that Phoenix adds to the Cowboy2 adapter. If you start the server yourself you would already be aware of the URL/port settings. It makes sense for higher level like Phoenix though.
So I think maybe this info log belongs in `Bandit.PhoenixAdapter` instead. It should maybe also have a pretty print of common errors just like the Cowboy2 adapter. Right now with `:eaddrinuse` it just shows this:
```
** (EXIT from #PID<0.13506.0>) shutdown: failed to start child: :listener
** (EXIT) :eaddrinuse
``` …

Adjustable info log for server startup

---

mix.exs

Got an error testing with Elixir 1.11, because of `Kernel.then/2` usage.
`mtrudel/elixir-ci-actions/.github/workflows/test.yml@main` tests from 1.12 so this was not caught, maybe it should explicitly test the lowest version supported just to ensure that there's no drift in the CI?

Require Elixir 1.12

---

test/bandit/http1/request_test.exs

When testing for invalid version, we should use a valid path. 
Otherwise the assert wouldn't fail when the version check fails, since the invalid path also returns `400` (with "Unsupported request target (RFC9112§3.2)")

Use valid path to avoid false negative

---

lib/bandit.ex
lib/bandit/http1/adapter.ex
lib/bandit/http1/handler.ex
lib/bandit/initial_handler.ex

I think we should avoid a nested lookup on every connection and set the `enabled` flags directly in the `handler_options` / `state`. 
WDYT?

Minor performance improvement

---

lib/bandit/http2/connection.ex

The documentation states:
> max_header_key_length: The maximum permitted length of any single header key (expressed as the number of decompressed bytes) in an HTTP/2 request. Defaults to 10_000 bytes
This isn't the case with `String.length/1` (which is also quite a bit slower than `byte_size/1`) since it counts multi-byte characters as 1.

Use `byte_size/1` instead of `String.length/1`

---

lib/bandit/headers.ex

Should it check that `port` matches `t:inet.port_number/0`?

Port number guard checks valid port range

---

.credo.exs
lib/bandit/compression.ex
lib/bandit/headers.ex
lib/bandit/http1/adapter.ex
lib/bandit/http1/handler.ex
lib/bandit/http2/frame.ex
lib/bandit/http2/stream.ex
lib/bandit/http2/stream_task.ex
lib/bandit/pipeline.ex
lib/bandit/websocket/connection.ex
lib/bandit/websocket/frame.ex
lib/bandit/websocket/handshake.ex
test/bandit/websocket/autobahn_test.exs
test/bandit/websocket/http1_handshake_test.exs
test/bandit/websocket/protocol_test.exs
test/bandit/websocket/sock_test.exs
test/bandit/websocket/upgrade_test.exs

Make it easier to configure how `credo` is run.
Example: CI uses `--strict`, so in the config I turned `strict` on by default to avoid running `mix credo` locally and thinking all is well before pushing.
Also added custom config for `Credo.Check.Design.AliasUsage` so we could remove some magic credo comments.
i.e.
```elixir
[
if_called_more_often_than: 1,
excluded_lastnames: defaults ++ ~w[Adapter Utils]
]
```
or could just disable the alias check altogether?
Could potentially do similar for `Credo.Check.Refactor.CyclomaticComplexity`.

Add credo config file

---

lib/bandit/headers.ex
test/bandit/headers_test.exs

I talked about it at the end of #145 although it's a micro-optimization.
I didn't know where to put it, I could put it as a private guard in the headers module? Or somewhere else?

Add a port number guard and use that in the checks instead of range

---

lib/bandit/headers.ex
test/bandit/headers_test.exs

I thought we could shave some performance out of integer parsing since we don't care about things like the base or negative integers. We have a specific case in this module of only caring about non-negative integers in base10.
I've also intentionally tried to optimize for the happy path.
```elixir
Mix.install([
{:benchee, "~> 1.0"}
])
numbers = Enum.map(0..999_999, &to_string/1)
defmodule Parser do
def parse_integer(binary) do
parse_integer(binary, [])
end
defp parse_integer(<<d::8, rest::binary>>, digits) when d >= ?0 and d <= ?9 do
parse_integer(rest, [d - ?0 | digits])
end
defp parse_integer(rest, [_ | _] = digits), do: {Enum.reverse(digits) |> undigits(0), rest}
defp parse_integer(_, []), do: :error
defp undigits([], acc), do: acc
defp undigits([digit | tail], acc) do
undigits(tail, …
```

Manually parse integers in headers module

---

lib/bandit/http1/adapter.ex
lib/bandit/http1/handler.ex
lib/bandit/http2/connection.ex

basred on @asakura's [recent work](https://github.com/mtrudel/thousand_island/pull/62) on Thousand Island, we should be smarter about handling errors when asking for information about local or peer info. Sadly, there's not much we can do in the case where we DO get errors back, but at least we're now erroring with something more clear than a match error.

Better handle errors from Thousand Island when unable to get local/peer info

---

lib/bandit/headers.ex
test/bandit/headers_test.exs

- added typespecs for the functions added in #148
- added tests for `get_content_length/1`(won't pass until we have a version with this PR https://github.com/elixir-plug/plug/pull/1155)
- made `parse_integer/1` private
- removed an unnecessary guard since the parser can never return a negative integer now
- removed tests for `parse_integer/1` (replaced by tests for get_content_length/1`)
It's easy to miss if skimming: the updated tests **won't pass** _until_ we have a version of `plug` with the above-mentioned PR.

Add typespecs to `Headers` module and remove unnecessary guard

---

lib/bandit/http1/adapter.ex

Currently all HTTPS connection via HTTP1 will fail, because a client certificate is required (?) when using TLS.
This changes the behavior to allow HTTPS connections without a client certificate

Fix failing connection when peer doesn't provide a certificate

---

test/bandit/http1/request_test.exs
test/bandit/http2/plug_test.exs
test/bandit/http2/protocol_test.exs
test/bandit/initial_handler_test.exs
test/bandit/websocket/protocol_test.exs
test/bandit/websocket/sock_test.exs
test/support/simple_h2_client.ex
test/support/simple_http1_client.ex
test/support/simple_websocket_client.ex
test/support/transport.ex

A small refactoring for the SimpleH2Client and SimpleHTTP1Client to support both transports (TCP and SSL) for both of the protocols (HTTP/1.1 and HTTP/2)

Refactor tests with adding Transport abstraction

---

lib/bandit/http1/adapter.ex
lib/bandit/http1/handler.ex
lib/bandit/http2/stream.ex
lib/bandit/http2/stream_task.ex
lib/bandit/telemetry.ex
test/bandit/http1/request_test.exs
test/bandit/http2/plug_test.exs
test/bandit/websocket/upgrade_test.exs

* Move `conn` into telemetry metadata
* Add `method`, `request_target` and `status` metadata to HTTP telemetry stop events
* Refactor HTTP/1 & HTTP/2 implementations to separate out request line parsing, in order to have access to method & request target for early errors

Refine telemetry behaviour in error cases 

---

lib/bandit.ex

Fix typo in  Bandit docs

---

lib/bandit/pipeline.ex
test/bandit/http1/request_test.exs
test/bandit/http2/protocol_test.exs

Fixes #106
Relevant to your interests @wkirschbaum

Use protocol default port in the event that no port is provided in host

---

lib/bandit/compression.ex
lib/bandit/http1/adapter.ex
lib/bandit/http2/adapter.ex
lib/bandit/http2/connection.ex
test/bandit/http1/request_test.exs
test/bandit/http2/protocol_test.exs

As noted in #230, there were a few places where we weren't optimally deflating iolist response bodies. This PR fixes those cases, as well as updates a few comparisons of the form `a == <<>>` with `byte_size(a) == 0` where we know for sure that `a` is a binary.

Improve handling of iolist response bodies

---

.credo.exs
lib/bandit/websocket/README.md
lib/bandit/websocket/handshake.ex
lib/bandit/websocket/upgrade_validation.ex
test/bandit/http1/request_test.exs
test/bandit/websocket/autobahn_test.exs
test/bandit/websocket/http1_handshake_test.exs
test/bandit/websocket/protocol_test.exs
test/bandit/websocket/sock_test.exs
test/bandit/websocket/upgrade_validation_test.exs

As part of the workup for https://github.com/phoenixframework/websock_adapter/issues/11, upgrade request validation is moving into the `WebSockAdapter.upgrade` call so that it can be surfaced to the caller at the time the upgrade request is made. As part of this work, the implementation there (which was initially based on the Bandit's implementation) was refactored pretty heavily, and looks a whole lot nicer now. 
This PR essentially brings those changes back to Bandit, so that they both look nicer! The tests are basically identical (and in a perfect world, would actually *be* the same implementation), but for simplicity's sake aren't DRYed up into a shared project (we can't just use one or the other due to the way Bandit and websock_adapter depend on one another). 
This PR is independent …

Refactor websocket upgrade validation

---

lib/bandit/http2/connection.ex
lib/bandit/http2/stream_collection.ex

This should have actually come out as part of https://github.com/mtrudel/bandit/pull/33 but was missed

Remove tracking of remote max_concurrent_streams

---

lib/bandit/websocket/handler.ex

See https://github.com/phoenixframework/websock_adapter/pull/15 for the reasoning. 
Felt like this was necessary here as well, but maybe bandit/thousand_island architecture wouldn't require it, I didn't really look deeply into it.

Add support to :max_heap_size in websocket handler

---

lib/bandit/phoenix_adapter.ex

Follows https://github.com/phoenixframework/phoenix/pull/5620

Add support for `Bandit.PhoenixAdapter.server_info/1`

---

lib/bandit/http1/handler.ex
lib/bandit/websocket/handler.ex
test/bandit/http1/request_test.exs

Previously, unexpected messages received by an HTTP/1 handler would crash the server; this PR updates this behaviour to log messages in the same way that a stock GenServer which does not implement any `handle_info/2` callbacks does, and thence does not crash. 
Note there's no need to add a similar mechanism on HTTP/2 handlers, since HTTP/2  requests are backed (at least for now) by `Task`
Also note that there's no need to add a similar mechanism to WebSockets, since WebSock already provides a way to forward handle_info calls to the websock implementor. In fact, this PR also stops explicitly catching normal monitored process termination calls in the websocket handler for this reason.

Tweaks to how Bandit handles unexpected messages

---

mix.exs

The initial goal for this change was to incorporate the CHANGELOG into the hex package so that it would be available in the diff tool on hex.pm or the command line (i.e. `mix hex.package diff bandit 1.1.0..1.1.1`).
Per discussion in mtrudel/bandit#265 we'll accomplish the above by removing the `files` configuration and relying on the default list of files provided by hex (see the linked issue for details).
This change will also have the effect of removing test files from future releases.
Resolves #265

Rely on default `files` list for hex package

---

lib/bandit.ex

Work was previously done to support non-typical values in the `:transport_options` for ThousandIsland with https://github.com/mtrudel/bandit/commit/43d49c8817b2c2f71bf4149036f5680dae36b02d.
However, if using SSL and including multiple key/value pairs with a non-typical, such as `:inet6`, it would still error because of an attempt to `Keyword.delete/2` out the `:otp_app` key.
This fixes that with `Enum.reject/2` to get the same behavior and still allow the list as expected by `:ssl` and `:gen_tcp`
<details><summary>Example Error</summary>
<p>
```
** (Mix) Could not start application nerves_hub: NervesHub.Application.start(:normal, []) returned an error: shutdown: failed to start child: NervesHubWeb.DeviceEndpoint
** (EXIT) shutdown: failed to start child: {NervesHubWeb.DeviceEndpoint, …
```

Fix `:transport_options` allowing non-typical values

---

mix.exs

Closes #265
Sanity check:
% mix hex.build --unpack -o pkg
% iex
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Interactive Elixir (1.17.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex> Mix.install([:req, {:bandit, path: "pkg"}])
iex> {:ok, _} = Bandit.start_link(scheme: :http, plug: fn conn, _ -> Plug.Conn.send_resp(conn, 200, "hi") end)
14:12:40.784 [info] Running #Function<41.105768164/2 in :erl_eval.expr/6> with Bandit 1.1.2 at 0.0.0.0:4000 (http)
iex> Req.get!("http://localhost:4000")
%Req.Response{
status: 200,
headers: %{
"cache-control" => ["max-age=0, private, must-revalidate"],
"date" => ["Fri, 29 Dec 2023 13:12:40 GMT"],
"vary" => ["accept-encoding"]
},
body: "hi",
trailers: %{},
private: %{}
}

Explicitly set Hex package files

---

lib/bandit/websocket/frame.ex

Late to the party, but suggesting a further optimization of #272 that avoids constructing the extra mask binary. With JIT improvements like https://github.com/erlang/otp/pull/5849 and https://github.com/erlang/otp/pull/7828 this could get better in future releases too.
On my system the benchmark from https://github.com/mtrudel/bandit/pull/272#issuecomment-1847571663 gives this ("proposed" being this PR):
```
Elixir 1.15.7
Erlang 26.2
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 2 s
reduction time: 0 ns
parallel: 1
inputs: lg, md, sm
Estimated total run time: 54 s
Benchmarking PR272 with input lg ...
Benchmarking PR272 with input md ...
Benchmarking PR272 with input sm ...
Benchmarking proposed with input lg ...
Benchmarking proposed with …
```

Further optimize websocket frame mask

---

lib/bandit/http1/handler.ex
test/bandit/http1/request_test.exs

Do not send a fallback if the plug has already sent a response

---

lib/bandit/http1/adapter.ex
test/bandit/http1/request_test.exs

Per https://hexdocs.pm/plug/Plug.Conn.Adapter.html#c:inform/3, the callback should return:
:ok | {:error, :not_supported}
The way Plug.Conn.inform! is implemented at the moment, https://github.com/elixir-plug/plug/blob/v1.15.2/lib/plug/conn.ex#L1335, it looked like Bandit did _not_ implement inform but it sure does!

Fix Bandit.HTTP1.Adapter.inform/3 return value

---

lib/bandit.ex
lib/bandit/http1/handler.ex
test/bandit/http1/request_test.exs

We end up unavoidably getting a lot of messages in our mailbox from phoenix long polling, and it's becoming a support burden. There's no loss of messages here, it's just a matter of not being so verbose by default.

Disable logging of unknown messages received by http/1 handler

---

lib/bandit/http1/adapter.ex
test/bandit/http1/request_test.exs

tldr; Is that certain clients (in this case apache bench) will send http/1.0 requests with "Keep-Alive" and not "keep-alive" and we currently don't respect that.
I noticed this issue while comparing ab to other servers which seem to handle this correctly. I originally asked about this behavior in the [elixir forums](https://elixirforum.com/t/bandit-keep-alives-not-working-in-apache-bench/61672)
After taking a look and doing some debugging I saw that we fail to lower-case the connection header prior to comparison. Instead of incurring the penalty of lower-casing the entire header I'm assuming the mixed-case pattern match is a performant solution? Strictly speaking we probably should lower-case it to be "compliant"
I did look at the `get_connection_header_keys/1` function but it didn't …

allow http/1.0 to work with mixed-case Keep-Alive

---

lib/bandit/http1/adapter.ex
test/bandit/http1/request_test.exs

In [RFC 7320 section 3.3.1](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.1), it states:
> A server MUST NOT send a Transfer-Encoding header field in any response with a status code of 1xx (Informational) or 204 (No Content).
this conditional brings Bandit into line with the RFC and Cowboy

don't send the transfer-encoding: chunked header for 100..199, 204

---

lib/bandit.ex
lib/bandit/http1/handler.ex
test/bandit/http1/request_test.exs
test/support/req_helpers.ex

As a potential fix to #320, add an option to disable the logging of protocol errors in HTTP/1. Logging is still enabled by default (at least for now; I'd like to get some idea of how many errors this ends up hiding before enabling by default). You can disable logging by:
```
config :my_phoenix_app, MyPhoenixAppWeb.Endpoint,
http: [
ip: ...,
port: ...,
http_1_options: [log_protocol_errors: false]
]
...
```

Provide config option to disable logging of protocol errors

---

lib/bandit.ex
lib/bandit/http1/handler.ex
test/bandit/http1/request_test.exs

Solves #313 
'n' defaults to 5, but is configurable using the `gc_every_n_keepalive_requests` http_1 option.

Run an explicit garbage collection between every 'n' keepalive requrests in HTTP/1

---

CHANGELOG.md
lib/bandit/exceptions.ex
lib/bandit/http1/adapter.ex
lib/bandit/http1/error.ex
lib/bandit/http1/handler.ex
lib/bandit/http1/socket.ex
lib/bandit/http_transport.ex
lib/bandit/pipeline.ex
lib/bandit/telemetry.ex
test/bandit/http1/request_test.exs
test/bandit/websocket/upgrade_test.exs

This is a long-term working branch to handle a fairly major refactor of the HTTP/1 code. Goals:
* Split HTTP/1-specific transport concerns out from higher level HTTP semantic concerns. Put the transport concerns (roughly, RFC9112 concerns) into Bandit.HTTP1.Socket, and HTTP semantic concerns (roughly, RFC9110 concerns) into Bandit.HTTP1.Adapter. Have the two talk to one another via the `Bandit.HTTPTransport` behaviour introduced in #286. 
* Get the HTTP/1 and H2 adapters looking more or less identical
A future PR will factor them together into a single implementation. This will prevent having to implement all HTTP semantic concerns separately in both stacks, as well as provide a framework for WebSocket support in HTTP/2

Refactor HTTP/1

---

CHANGELOG.md
lib/bandit.ex
lib/bandit/adapter.ex
lib/bandit/headers.ex
lib/bandit/http1/error.ex
lib/bandit/http1/handler.ex
lib/bandit/http1/socket.ex
lib/bandit/http2/connection.ex
lib/bandit/http2/stream.ex
lib/bandit/http2/stream_process.ex
lib/bandit/http_error.ex
lib/bandit/http_transport.ex
lib/bandit/pipeline.ex
lib/bandit/telemetry.ex
lib/bandit/transport_info.ex
lib/bandit/websocket/connection.ex
lib/bandit/websocket/handler.ex
test/bandit/headers_test.exs
test/bandit/http1/request_test.exs
test/bandit/http2/plug_test.exs
test/bandit/http2/protocol_test.exs
test/bandit/websocket/sock_test.exs

DRYs up a bunch of logic in `Bandit.HTTP1.Handler` and `Bandit.HTTP2.StreamProcess`, folding it into a common path in `Bandit.Pipeline`

Refactor pipeline

---

lib/bandit/http1/socket.ex
lib/bandit/http2/stream.ex
test/bandit/http1/request_test.exs
test/bandit/http2/plug_test.exs
test/bandit/http2/protocol_test.exs
test/bandit/initial_handler_test.exs
test/bandit/websocket/protocol_test.exs
test/bandit/websocket/sock_test.exs
test/bandit/websocket/upgrade_test.exs

With one (separately committed) exception (and a few minor typo fixes), no actual test changes

Refine tests to not implicitly capture output

---

lib/bandit.ex
lib/bandit/phoenix_adapter.ex
test/bandit/server_test.exs

Done in to the Phoenix adapter because it's an oddball thing that I don't want Bandit to support at the top level. It's a shim, not a feature.

Support top-level :inet and :inet6 options in Phoenix

---

lib/bandit.ex
lib/bandit/http1/socket.ex
lib/bandit/http2/stream.ex
lib/bandit/http_error.ex
lib/bandit/pipeline.ex
test/bandit/http1/request_test.exs
test/bandit/http2/plug_test.exs
test/bandit/http2/protocol_test.exs
test/support/safe_error.ex

Improve error handling from plug-surfaced errors

---

lib/bandit/adapter.ex
lib/bandit/headers.ex
test/bandit/http1/request_test.exs
test/bandit/http2/plug_test.exs

I have an application that streams extremely large payloads. Due to reasons beyond my control, HEAD requests must respond with HTTP status 200, so my Plug handler sends with:
```elixir
conn
|> Plug.Conn.put_resp_header("content-length", payload_size)
|> Plug.Conn.send_resp(200, "")
```
However, `Bandit.Headers.add_content_length/3` replaces my application's "content-length" header with `content-length: 0`. 
As it stands the only way for me to set "content-length" on a HEAD 200 response seems to be to either wastefully render the full response or allocate a body of "content-length"-size and pass it into `send_resp`, but this is not practical or efficient. It also seems to violate the spirit of [RFC9110 § 9.3.2](https://www.rfc-editor.org/rfc/rfc9110.html#HEAD):
>  A client SHOULD NOT …

Respect pre-computed content-length for HEAD responses

---

lib/bandit/adapter.ex
lib/bandit/http1/socket.ex
test/bandit/http1/request_test.exs
test/support/transport.ex

The Plug spec doesn't really provide for the effective surfacing of errors from send calls, mostly because Cowboy will (usually) have killed off the connection handler process when the client closes the connection. In Bandit's case, we don't actively kill off connection processes in this situation, so we need to be able to surface these cases effectively. Raising a `Bandit.HTTPError` will bubble through the caller all the way up to Bandit's handler pipeline, and log the error as configured. This is as good of a pattern as we're going to have, and mirrors what we do for reads against closed clients already (tests were added for that case here as well, since they were absent before). 
Fixes #344

Raise error on send errors for HTTP/1 responses

---

lib/bandit/http2/stream.ex
test/bandit/http2/plug_test.exs

Read data during stream shutdown to ensure we update expected content-length

---

lib/bandit/http1/socket.ex
test/bandit/http1/request_test.exs

Expose body read timeouts as 408 Request Timeout errors

---

lib/bandit/extractor.ex
lib/bandit/websocket/extractor.ex
lib/bandit/websocket/frame.ex
lib/bandit/websocket/handler.ex
test/bandit/websocket/frame_deserialization_test.exs
test/bandit/websocket/protocol_test.exs

Fixes #389
This is a significant refactor of the initial proposed solution, but the core idea is the same: when parsing a frame, gather enough bytes to parse the header, and then start receiving the payload data into an iolist until the number of payload bytes is satisfied.

Build iolist for WebSocket frame data

---

lib/bandit.ex
lib/bandit/http2/handler.ex
lib/bandit/pipeline.ex
test/bandit/http1/request_test.exs

Created as a result from [this discussion](https://github.com/mtrudel/bandit/issues/391#issuecomment-2343662062)
This PR adds a new http option, `log_client_closures`, that allows users to silence `Bandit.HTTP` errors that stem from clients closing the connection. The option defaults to `false`.

Add log_client_closures http option

---

lib/bandit/pipeline.ex
test/bandit/http1/request_test.exs

feat: lets `:logger` handlers know about the original exception

---

test/bandit/server_test.exs

Very minor dev ergnomics thing.
When working on previous PRs, I sometimes got eaddrinuse locally while occasionally running bandit test because of having other phoenix apps on default 4000 on the side :slightly_smiling_face:

test: make less likely that test run into :eaddrinuse failure locally

---

lib/bandit/pipeline.ex
test/bandit/http1/request_test.exs

Following up #417.
Another piece that helps switch from `plug_cowboy` to `bandit` without losing features in this Error Tracking / Logging area.
In `plug_cowboy`: https://github.com/elixir-plug/plug_cowboy/pull/57.
Example of a logger handler that consumes the `conn` made available as metadata by plug_cowboy:
- `logger_json`: https://hexdocs.pm/logger_json/LoggerJSON.html#module-metadata.

feat: allow logger handler to know about HTTP request details

---

lib/bandit/adapter.ex
lib/bandit/compression.ex
test/bandit/http1/request_test.exs
test/bandit/http2/protocol_test.exs

Adds support for deflating chunked responses. Consists of a refactor to first break apart the existing compression routines such that the constituent stages can be called separately throughout the lifecycle of a chunked response, and then using these new routines within chunked responses.
Only deflate is supported on responses

Deflate support on chunked responses

---

lib/bandit/adapter.ex
lib/bandit/compression.ex
test/bandit/http1/request_test.exs
test/bandit/http2/protocol_test.exs

Re-opening of #421, which GitHub got confused about after I forced pushed it away

Deflate support on chunked responses (take 2)

---

lib/bandit/http1/socket.ex
test/bandit/http1/request_test.exs

Previously this field represented the bytes still to read off the wire, as opposed to the bytes still required per the request's content length. This made it hard to support cases where we *wanted* to maintain a buffer
of pipelined requests after the current request's body (previously, we just errored loudly on this in the assumption that it represented an intentionally misbehaving client).
Fix this by using an `undefined_content_length` parameter on HTTP/1 requests that instead represents the pending bytes *on this request* so that we can more easily handle the case where the socket buffer contains bytes belonging to the subsequent request.
@woylie relevant to your interests

Fixup POST pipeline support

---

lib/bandit.ex
lib/bandit/http2/connection.ex
lib/bandit/http2/handler.ex
lib/bandit/initial_handler.ex
lib/bandit/logger.ex
lib/bandit/pipeline.ex

Add plug to logging metadata

---

lib/bandit/initial_handler.ex

Read a minimal number of bytes when sniffing for protocol

---

lib/bandit/telemetry.ex
test/bandit/http1/request_test.exs
test/bandit/http2/plug_test.exs

Relevant to your interests @martasaur. 
@bryannaegele, is this compatible downstream as-is? Any changes I can / should make to help if not?

Add support for sending telemetry events on throws and exits

---

lib/bandit/pipeline.ex
test/bandit/http1/plug_test.exs

Fixes #451 
Previously, Bandit would keep the connection open for errors which it did not log; this was an oversight.

Always close HTTP/1 connection in any case where an error comes out of the plug

---

lib/bandit/pipeline.ex
test/bandit/http1/plug_test.exs

Hi there :wave: 
Minor follow up for https://github.com/mtrudel/bandit/commit/a053c1cd95d90756bf1dd6927199f8f2afc5b9fb.
Analogous code in `plug_cowboy`: https://github.com/elixir-plug/plug_cowboy/blob/ced253f035f2a07ebed17cfacb64d4f16357a750/lib/plug/cowboy/handler.ex#L51-L55.
Thanks!

fix: properly normalize erlang errors before emitting telemetry and logged crash_reason

---

lib/bandit/websocket/handshake.ex
test/bandit/websocket/protocol_test.exs
test/bandit/websocket/upgrade_test.exs
test/support/simple_websocket_client.ex

Fixes #457, which was introduced in #428
@peaceful-james is it possible for you to re-test that the original issue from #422 is still fixed with this branch?

Send any headers already queued in the plug when upgrading websocket

---

test/support/req_helpers.ex

ex_unit context `:case` no longer available since:
https://github.com/elixir-lang/elixir/commit/ecac839810905f2da826c5cca01cb4e0e9fc5a95

test: fixes tests in Elixir 1.18

---

mix.exs

• Adds changelog link to hexdocs for easier access from package page
• Complements existing changelog configuration in docs extras

Add changelog link to package metadata

---

README.md

Very minor PR but when swapping out `Plug.Cowboy` for `Bandit` we were only pulling in version `1.6.11` when the including `{:bandit, "~> 1.0"}` in our `mix.exs`:
However `{:bandit, "~> 1.8"}` ensured we had the correct version:
I haven't updated it in the `lib/bandit/phoenix_adapter.ex` documentation as the latest version of Phoenix seems to use `1.6.7`:
https://github.com/phoenixframework/phoenix/blob/v1.8.0/mix.lock#L2

Update version to `1.8`  in README

---

lib/bandit/http2/errors.ex
lib/bandit/http2/flow_control.ex
lib/bandit/http2/stream.ex
lib/bandit/logger.ex
test/bandit/http2/protocol_test.exs

Splitting from https://github.com/mtrudel/bandit/pull/520, this only adds the stream_id to the StreamError exceptions.

Pass stream_id to StreamError exceptions
