.gitignore, README.md, lib/bandit.ex, lib/bandit/http1/handler.ex, lib/bandit/websocket/connection.ex, lib/bandit/websocket/frame.ex, lib/bandit/websocket/frame/binary.ex, lib/bandit/websocket/frame/connection_close.ex, lib/bandit/websocket/frame/continuation.ex, lib/bandit/websocket/frame/ping.ex, lib/bandit/websocket/frame/pong.ex, lib/bandit/websocket/frame/text.ex, lib/bandit/websocket/handler.ex, lib/bandit/websocket/handshake.ex, lib/bandit/websocket/permessage_deflate.ex, lib/bandit/websocket/socket.ex, test/bandit/http1/request_test.exs, test/bandit/websocket/autobahn_test.exs, test/bandit/websocket/frame_deserialization_test.exs, test/bandit/websocket/frame_serialization_test.exs, test/bandit/websocket/http1_handshake_test.exs, test/bandit/websocket/protocol_test.exs, test/bandit/websocket/sock_test.exs, test/support/autobahn_config.json, test/support/simple_websocket_client.ex
~Waiting on #38, which is in turn waiting on phoenixframework/phoenix#5030 and the work therein.~ Ready for review. @moogle19 care to have a gander?
=> Implement WebSocket extension + permessage-deflate support

.github/dependabot.yml, README.md, SECURITY.md
Based on a walk of the Security tab in GitHub
=> Define security policy

lib/bandit/http1/adapter.ex
🏌️ As discussed https://github.com/mtrudel/bandit/pull/42#discussion_r1019619895
=> Convert `case` with passthrough errors to `with` in `Bandit.HTTP1.Adapter`

.github/workflows/benchmark.yml
Triggers when the label 'benchmark' is added to any PR, and any commit to a PR so labeled
=> Add Benchmark CI

.github/workflows/benchmark.yml, mix.exs, test/bandit/clock_test.exs, test/bandit/http1/request_test.exs, test/bandit/http2/plug_test.exs, test/bandit/http2/protocol_test.exs, test/bandit/initial_handler_test.exs, test/bandit/websocket/http1_handshake_test.exs, test/support/simple_h2_client.ex, test/support/simple_http1_client.ex, test/support/simple_websocket_client.ex, test/test_helper.exs
No functional changes, just tests
=> Tighten up & refactor test code

lib/bandit/http1/adapter.ex, lib/bandit/http1/handler.ex, test/bandit/http1/request_test.exs, test/bandit/websocket/http1_handshake_test.exs
For improved speed / memory use
=> Manually build URI instead of using URI.parse/1 in HTTP/1 adapter

lib/bandit/headers.ex, lib/bandit/http1/adapter.ex, lib/bandit/http1/handler.ex, lib/bandit/http2/adapter.ex, lib/bandit/http2/connection.ex, lib/bandit/http2/stream.ex, lib/bandit/http2/stream_task.ex, lib/bandit/pipeline.ex, test/bandit/http1/request_test.exs, test/bandit/http2/plug_test.exs, test/bandit/http2/protocol_test.exs
Shared concerns for URI building, Conn handling, etc. Also brings improved URI building to h2
=> Factor out a common HTTP pipeline

lib/bandit/http1/adapter.ex, lib/bandit/http1/handler.ex
=> Fixup error handling in HTTP/1

lib/bandit/http1/adapter.ex
Trial to see if this is faster
=> Use _bin decode_packet variant

lib/bandit/websocket/connection.ex
Check two ranges instead of three.
=> Change close code guard to favour happy path

README.md, lib/bandit.ex, lib/bandit/compression.ex, lib/bandit/http1/adapter.ex, lib/bandit/http2/adapter.ex, lib/bandit/http2/connection.ex, lib/bandit/http2/stream.ex, lib/bandit/telemetry.ex, test/bandit/http1/request_test.exs, test/bandit/http2/plug_test.exs, test/bandit/http2/protocol_test.exs
More config / metrics / docs pending
=> Add HTTP Compression

lib/bandit/websocket/connection.ex, test/bandit/websocket/sock_test.exs
Can be safely merged ahead of https://github.com/phoenixframework/websock/pull/7
=> Make WebSock.terminate/2 optional

lib/bandit/http1/handler.ex, lib/bandit/http2/handler.ex, lib/bandit/websocket/handler.ex, test/bandit/http1/request_test.exs
This is (I believe) the underlying cause of https://github.com/mtrudel/thousand_island/issues/52.
=> Improve read_timeout consistency

lib/bandit/websocket/handshake.ex, test/bandit/http1/request_test.exs, test/support/simple_http1_client.ex
=> Improve WebSocket upgrade error checking

lib/bandit/pipeline.ex, test/bandit/http1/request_test.exs, test/bandit/http2/protocol_test.exs
=> Use declared scheme even if it does not match the transport

lib/bandit/http1/adapter.ex
It was difficult to measure impact of the changes provided, but I hope that 
* the compiler can inline specialized version of the read function which would lead to less instructions executed in runtime
* passing around refs to variables faster than changing content of a map
=> Reduce amount of work HTTP1 Adapter's do to ready body chunks

lib/bandit/http1/adapter.ex
Makes no sense since this was changed a few days ago.
=> Remove comment that no longer makes sense

lib/bandit/pipeline.ex
Addressing @moogle19 code readability and compatibility concerns
=> Fix 175 like Cowboy does :)

lib/bandit/http1/adapter.ex, test/bandit/http1/request_test.exs
Duplicates #183 
Fixes #182
Related to #169
=> Simplify content-length body reading

lib/bandit/http1/adapter.ex, test/bandit/http1/request_test.exs, test/support/simple_http1_client.ex
=> Add support for HTTP/1.1 inform calls

lib/bandit.ex, lib/bandit/http1/adapter.ex, lib/bandit/pipeline.ex, lib/bandit/websocket/frame.ex
Fix some typespecs and add cases for `:undefined` and `:unspec` in `bound_address/2`
=> Fix Typespecs

lib/bandit/http1/adapter.ex, test/bandit/http1/request_test.exs
=> Return errors from chunk/2 calls in HTTP/1

lib/bandit/http2/connection.ex, lib/bandit/http2/handler.ex, lib/bandit/http2/stream.ex
Reverts #117
Fixes #215
Relevant to your interests @danschultzer
=> Revert "Stop requiring HTTP/2 adapter commands to come from stream owner"

lib/bandit.ex, lib/bandit/pipeline.ex, test/bandit/http1/request_test.exs, test/bandit/http2/plug_test.exs
=> Support function based plugs

lib/bandit/http1/adapter.ex, lib/bandit/http1/handler.ex, test/bandit/http1/request_test.exs
=> Read body between keepalives

lib/bandit.ex, test/bandit/initial_handler_test.exs, test/bandit/websocket/upgrade_test.exs
=> Do not advertise disabled protocols via ALPN

lib/bandit/http1/socket.ex
Fixes a substantial (20%+) perf regression introduced by #297
=> Coalesce header and body calls together in the common 'plain' body send case

lib/bandit/http1/handler.ex, test/bandit/http1/request_test.exs
=> Only save Process keys that are atoms starting with $

lib/bandit/pipeline.ex, lib/bandit/telemetry.ex, test/bandit/http1/request_test.exs, test/bandit/http2/plug_test.exs
closes #410.
An re-worked attempt after #396, trying to improve it by taking some pieces from #398.
=> fix: throwing plug properly handled and returns 500

lib/bandit/adapter.ex, lib/bandit/http1/socket.ex, lib/bandit/http2/errors.ex, lib/bandit/http2/stream.ex, lib/bandit/pipeline.ex, lib/bandit/socket_error.ex, lib/bandit/transport_error.ex, test/bandit/http1/request_test.exs, test/bandit/http2/protocol_test.exs
=> Improve unrecoverable error handling

lib/bandit/http1/handler.ex, lib/bandit/http1/socket.ex, test/bandit/http1/request_test.exs
Fixes the underlying issue in #431.
=> Handle pipelined requests

lib/bandit/pipeline.ex, lib/bandit/telemetry.ex, lib/bandit/websocket/connection.ex, test/bandit/http1/request_test.exs, test/bandit/http2/plug_test.exs, test/bandit/websocket/sock_test.exs, test/bandit/websocket/upgrade_test.exs
=> Add telemetry metadata

lib/bandit/adapter.ex
Future Plug versions will no longer emit the event automatically.
=> Emit already_sent event in adapter

lib/bandit/websocket/connection.ex
=> Close the deflation context *after* the socket close callback

lib/bandit/http1/socket.ex, lib/bandit/http2/stream.ex, test/bandit/http1/protocol_test.exs, test/bandit/http2/protocol_test.exs
=> Order headers

lib/bandit/http2/connection.ex, lib/bandit/http2/frame/settings.ex, test/bandit/http2/frame_deserialization_test.exs, test/bandit/http2/frame_serialization_test.exs, test/bandit/http2/protocol_test.exs
=> Merge received HTTP/2 settings with existing ones

lib/bandit/adapter.ex
See that Plug.Static already does this:
https://github.com/elixir-plug/plug/blob/87ae72ea2e21dd580df1367bdc709a84f75b87bd/lib/plug/static.ex#L137
=> Use raw mode to read from the file info
